### ISSUE TITLE
init-lab

### ISSUE THREAD

**Issue by LamchatabAmine** [labs-web/lab-authentification#6]
# init-lab

## Travail à faire

- Creation d'une rapport sans contenu, mais avec les titres des diapositives
- ajouter le lien du rapport dans README.md et README.json

## Livrable

- docs/*
- README.md
- README.json

**Comment by essarraj-fouad** [comment]
Le lien du rapport dans le fichier Readme n'est pas valide

**Comment by essarraj-fouad** [comment]
Il n'existe pas un pullrequest ouvert
