### ISSUE TITLE
init-présentation

### ISSUE THREAD

**Issue by LamchatabAmine** [labs-web/lab-authentification#7]
# init-présentation

## Travail à faire

- Création d'une présentation sans contenu, mais avec les titres des diapositives
- ajouter le lien du rapport dans README.md et README.json

## Livrable

- docs/*
- README.md
- README.json

**Comment by zaani12** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by essarraj-fouad** [comment]
Lien du présentation dans le fichier README n'est pas valide

**Comment by essarraj-fouad** [comment]
Il existe des conflits
